#include <TCanvas.h>
#include <TF1.h>
#include <TFile.h>
#include <TH1.h>
#include <TROOT.h>
#include <TStyle.h>

#include <array>
#include <iostream>
#include <string>

void histos()
{
	const std::array<std::string, 7> particleTypes{"pi+", "pi-", "K+", "K-", "p+", "p-", "K*"};

	auto* inFile{new TFile{"build/histos.root"}};

	// Load histograms from file
	auto* hParticleTypes{dynamic_cast<TH1I*>(inFile->Get("hParticleTypes"))};
	auto* hPhi{dynamic_cast<TH1D*>(inFile->Get("hPhi"))};
	auto* hTheta{dynamic_cast<TH1D*>(inFile->Get("hTheta"))};
	auto* hImpulse{dynamic_cast<TH1D*>(inFile->Get("hImpulse"))};
	auto* hTransverseImpulse{dynamic_cast<TH1D*>(inFile->Get("hTransverseImpulse"))};
	auto* hEnergy{dynamic_cast<TH1D*>(inFile->Get("hEnergy"))};
	auto* hInvMass{dynamic_cast<TH1D*>(inFile->Get("hInvMass"))};
	auto* hInvMassSameSign{dynamic_cast<TH1D*>(inFile->Get("hInvMassSameSign"))};
	auto* hInvMassDiscSign{dynamic_cast<TH1D*>(inFile->Get("hInvMassDiscSign"))};
	auto* hInvMassPiKSame{dynamic_cast<TH1D*>(inFile->Get("hInvMassPiKSame"))};
	auto* hInvMassPiKDisc{dynamic_cast<TH1D*>(inFile->Get("hInvMassPiKDisc"))};
	auto* hInvMassChildren{dynamic_cast<TH1D*>(inFile->Get("hInvMassChildren"))};
	auto* hInvMassSubAll{dynamic_cast<TH1D*>(inFile->Get("hInvMassSubAll"))};
	auto* hInvMassSubPiK{dynamic_cast<TH1D*>(inFile->Get("hInvMassSubPiK"))};

	std::cout << "Particles generated by type:\n";
	for (size_t i{0}; i < particleTypes.size(); ++i)
	{
		std::cout << particleTypes[i] << ": " << hParticleTypes->GetBinContent(i + 1) << " +/- "
				  << hParticleTypes->GetBinError(i + 1) << '\n';
	}

	TF1* fUnifTheta{new TF1{"fUnifTheta", "[0]", 0., TMath::Pi()}};
	fUnifTheta->SetParameter(0, 20'000);
	hTheta->Fit(fUnifTheta, "QN");
	std::cout << "Theta fit: " << fUnifTheta->GetParameter(0) << " +/- " << fUnifTheta->GetParError(0) << '\n';
	std::cout << "Theta chi2/NDF: " << fUnifTheta->GetChisquare() / fUnifTheta->GetNDF() << '\n';
	std::cout << "Theta chi2 prob: " << fUnifTheta->GetProb() << '\n';

	TF1* fUnifPhi{new TF1{"fUnifPhi", "[1]", 0., TMath::TwoPi()}};
	fUnifPhi->SetParameter(1, 20'000);
	hPhi->Fit(fUnifPhi, "QN");
	std::cout << "Phi fit: " << fUnifPhi->GetParameter(1) << " +/- " << fUnifPhi->GetParError(1) << '\n';
	std::cout << "Phi chi2/NDF: " << fUnifPhi->GetChisquare() / fUnifPhi->GetNDF() << '\n';
	std::cout << "Phi chi2 prob: " << fUnifPhi->GetProb() << '\n';

	TF1* fExpImpulse{new TF1{"fExpImpulse", "expo(2)", 0., 5.}};
	fExpImpulse->SetParameter(2., 1.);
	fExpImpulse->SetParameter(3., 1.);
	hImpulse->Fit(fExpImpulse, "QN");
	std::cout << "Impulse fit amplitude: " << fExpImpulse->GetParameter(2) << " +/- " << fExpImpulse->GetParError(2)
			  << '\n';
	std::cout << "Impulse fit decay: " << fExpImpulse->GetParameter(3) << " +/- " << fExpImpulse->GetParError(3)
			  << '\n';
	std::cout << "Impulse chi2/NDF: " << fExpImpulse->GetChisquare() / fExpImpulse->GetNDF() << '\n';
	std::cout << "Impulse chi2 prob: " << fExpImpulse->GetProb() << '\n';

	TF1* fGausAll{new TF1{"fGausAll", "gausn(4)", 0., 5.}};
	fGausAll->SetParameter(4, 800.);
	fGausAll->SetParameter(5, 0.9);
	fGausAll->SetParameter(6, 0.05);
	hInvMassSubAll->Fit(fGausAll, "QN");
	for (int i{4}; i < 7; ++i)
	{
		std::cout << "GausAll fit parameter " << i << ": " << fGausAll->GetParameter(i) << " +/- "
				  << fGausAll->GetParError(i) << '\n';
	}
	std::cout << "GausAll chi2/NDF: " << fGausAll->GetChisquare() / fGausAll->GetNDF() << '\n';
	std::cout << "GausAll chi2 prob: " << fGausAll->GetProb() << '\n';

	TF1* fGausPiK{new TF1{"fGausPiK", "gausn(4)", 0., 5.}};
	fGausPiK->SetParameter(4, 800.);
	fGausPiK->SetParameter(5, 0.9);
	fGausPiK->SetParameter(6, 0.05);
	hInvMassSubPiK->Fit(fGausPiK, "QN");
	for (int i{4}; i < 7; ++i)
	{
		std::cout << "GausPiK fit parameter " << i << ": " << fGausPiK->GetParameter(i) << " +/- "
				  << fGausPiK->GetParError(i) << '\n';
	}
	std::cout << "GausPiK chi2/NDF: " << fGausPiK->GetChisquare() / fGausPiK->GetNDF() << '\n';
	std::cout << "GausPiK chi2 prob: " << fGausPiK->GetProb() << '\n';

	std::array<TCanvas*, 14> canvases;
	gROOT->SetBatch(kTRUE);
	canvases[0] = new TCanvas{"cParticleTypes", "Particle types", 800, 600};
	hParticleTypes->Draw();
	canvases[1] = new TCanvas{"cPhi", "Phi", 800, 600};
	hPhi->Draw();
	canvases[2] = new TCanvas{"cTheta", "Theta", 800, 600};
	hTheta->Draw();
	canvases[3] = new TCanvas{"cImpulse", "Impulse", 800, 600};
	hImpulse->Draw();
	canvases[4] = new TCanvas{"cTransverseImpulse", "Transverse impulse", 800, 600};
	hTransverseImpulse->Draw();
	canvases[5] = new TCanvas{"cEnergy", "Energy", 800, 600};
	hEnergy->Draw();
	canvases[6] = new TCanvas{"cInvMass", "Invariant mass", 800, 600};
	hInvMass->Draw();
	canvases[7] = new TCanvas{"cInvMassSameSign", "Invariant mass same sign", 800, 600};
	hInvMassSameSign->Draw();
	canvases[8] = new TCanvas{"cInvMassDiscSign", "Invariant mass disc sign", 800, 600};
	hInvMassDiscSign->Draw();
	canvases[9] = new TCanvas{"cInvMassPiKSame", "Invariant mass pi K same", 800, 600};
	hInvMassPiKSame->Draw();
	canvases[10] = new TCanvas{"cInvMassPiKDisc", "Invariant mass pi K disc", 800, 600};
	hInvMassPiKDisc->Draw();
	canvases[11] = new TCanvas{"cInvMassChildren", "Invariant mass children", 800, 600};
	hInvMassChildren->Draw();
	canvases[12] = new TCanvas{"cInvMassSubAll", "Invariant mass sub all", 800, 600};
	hInvMassSubAll->Draw();
	canvases[13] = new TCanvas{"cInvMassSubPiK", "Invariant mass sub pi K", 800, 600};
	hInvMassSubPiK->Draw();

	system("mkdir -p build/pdf");
	system("mkdir -p build/C");
	system("mkdir -p build/root");
	for (auto* canvas : canvases)
	{
		canvas->Print((std::string{"build/pdf/"} + canvas->GetName() + ".pdf").c_str());
		canvas->Print((std::string{"build/C/"} + canvas->GetName() + ".C").c_str());
		canvas->Print((std::string{"build/root/"} + canvas->GetName() + ".root").c_str());
	}
}