#include <TCanvas.h>
#include <TF1.h>
#include <TFile.h>
#include <TH1.h>
#include <TROOT.h>
#include <TStyle.h>

#include <array>
#include <iostream>
#include <string>

void setStyle()
{
	gROOT->SetStyle("Plain");
	gStyle->SetPalette(57);
	gStyle->SetOptTitle(0);
	gStyle->SetOptFit(1111);
}

void setFitStyle(TF1* f)
{
	f->SetLineColor(kRed);
	f->SetLineStyle(1);
	f->SetLineWidth(2);
}

void histos()
{
	auto* inFile{new TFile{"build/histos.root"}};

	// Load histograms from file
	auto* hParticleTypes{dynamic_cast<TH1I*>(inFile->Get("hParticleTypes"))};
	auto* hPhi{dynamic_cast<TH1D*>(inFile->Get("hPhi"))};
	auto* hTheta{dynamic_cast<TH1D*>(inFile->Get("hTheta"))};
	auto* hImpulse{dynamic_cast<TH1D*>(inFile->Get("hImpulse"))};
	auto* hTransverseImpulse{dynamic_cast<TH1D*>(inFile->Get("hTransverseImpulse"))};
	auto* hEnergy{dynamic_cast<TH1D*>(inFile->Get("hEnergy"))};
	auto* hInvMass{dynamic_cast<TH1D*>(inFile->Get("hInvMass"))};
	auto* hInvMassSameSign{dynamic_cast<TH1D*>(inFile->Get("hInvMassSameSign"))};
	auto* hInvMassDiscSign{dynamic_cast<TH1D*>(inFile->Get("hInvMassDiscSign"))};
	auto* hInvMassPiKSame{dynamic_cast<TH1D*>(inFile->Get("hInvMassPiKSame"))};
	auto* hInvMassPiKDisc{dynamic_cast<TH1D*>(inFile->Get("hInvMassPiKDisc"))};
	auto* hInvMassDecayProd{dynamic_cast<TH1D*>(inFile->Get("hInvMassDecayProd"))};
	auto* hInvMassSubAll{dynamic_cast<TH1D*>(inFile->Get("hInvMassSubAll"))};
	auto* hInvMassSubPiK{dynamic_cast<TH1D*>(inFile->Get("hInvMassSubPiK"))};

	const std::array<std::string, 7> particleTypes{"pi+", "pi-", "K+", "K-", "p+", "p-", "K*"};

	std::cout << "Particles generated by type:\n";
	for (size_t i{0}; i < particleTypes.size(); ++i)
	{
		std::cout << particleTypes[i] << ": " << hParticleTypes->GetBinContent(i + 1) << " +/- "
				  << hParticleTypes->GetBinError(i + 1) << '\n';
	}

	auto* fUnifTheta{new TF1{"fUnifTheta", "pol0", 0., TMath::Pi()}};
	setFitStyle(fUnifTheta);
	fUnifTheta->SetParameter(0, 20'000);
	hTheta->Fit(fUnifTheta, "QN");
	std::cout << "Theta fit: " << fUnifTheta->GetParameter(0) << " +/- " << fUnifTheta->GetParError(0) << '\n';
	std::cout << "Theta chi2/NDF: " << fUnifTheta->GetChisquare() / fUnifTheta->GetNDF() << '\n';
	std::cout << "Theta chi2 prob: " << fUnifTheta->GetProb() << '\n';
	std::cout << "Theta NDF: " << fUnifTheta->GetNDF() << '\n';

	auto* fUnifPhi{new TF1{"fUnifPhi", "pol0", 0., TMath::TwoPi()}};
	setFitStyle(fUnifPhi);
	fUnifPhi->SetParameter(0, 20'000);
	hPhi->Fit(fUnifPhi, "QN");
	std::cout << "Phi fit: " << fUnifPhi->GetParameter(0) << " +/- " << fUnifPhi->GetParError(0) << '\n';
	std::cout << "Phi chi2/NDF: " << fUnifPhi->GetChisquare() / fUnifPhi->GetNDF() << '\n';
	std::cout << "Phi chi2 prob: " << fUnifPhi->GetProb() << '\n';
	std::cout << "Phi NDF: " << fUnifPhi->GetNDF() << '\n';

	auto* fExpImpulse{new TF1{"fExpImpulse", "expo", 0., 5.}};
	setFitStyle(fExpImpulse);
	fExpImpulse->SetLineWidth(1);
	fExpImpulse->SetParameter(0, 1.);
	fExpImpulse->SetParameter(1, 1.);
	hImpulse->Fit(fExpImpulse, "QN");
	std::cout << "Impulse fit amplitude: " << fExpImpulse->GetParameter(0) << " +/- " << fExpImpulse->GetParError(0)
			  << '\n';
	std::cout << "Impulse fit decay: " << fExpImpulse->GetParameter(1) << " +/- " << fExpImpulse->GetParError(1)
			  << '\n';
	std::cout << "Impulse chi2/NDF: " << fExpImpulse->GetChisquare() / fExpImpulse->GetNDF() << '\n';
	std::cout << "Impulse chi2 prob: " << fExpImpulse->GetProb() << '\n';
	std::cout << "Impulse NDF: " << fExpImpulse->GetNDF() << '\n';

	auto* fGausAll{new TF1{"fGausAll", "gausn", 0., 5.}};
	setFitStyle(fGausAll);
	fGausAll->SetParameter(0, 800.);
	fGausAll->SetParameter(1, 0.9);
	fGausAll->SetParameter(2, 0.05);
	hInvMassSubAll->Fit(fGausAll, "QN");
	for (int i{0}; i < 3; ++i)
	{
		std::cout << "GausAll fit parameter " << i << ": " << fGausAll->GetParameter(i) << " +/- "
				  << fGausAll->GetParError(i) << '\n';
	}
	std::cout << "GausAll chi2/NDF: " << fGausAll->GetChisquare() / fGausAll->GetNDF() << '\n';
	std::cout << "GausAll chi2 prob: " << fGausAll->GetProb() << '\n';
	std::cout << "GausAll NDF: " << fGausAll->GetNDF() << '\n';

	auto* fGausPiK{new TF1{"fGausPiK", "gausn", 0., 5.}};
	setFitStyle(fGausPiK);
	fGausPiK->SetParameter(0, 800.);
	fGausPiK->SetParameter(1, 0.9);
	fGausPiK->SetParameter(2, 0.05);
	hInvMassSubPiK->Fit(fGausPiK, "QN");
	for (int i{0}; i < 3; ++i)
	{
		std::cout << "GausPiK fit parameter " << i << ": " << fGausPiK->GetParameter(i) << " +/- "
				  << fGausPiK->GetParError(i) << '\n';
	}
	std::cout << "GausPiK chi2/NDF: " << fGausPiK->GetChisquare() / fGausPiK->GetNDF() << '\n';
	std::cout << "GausPiK chi2 prob: " << fGausPiK->GetProb() << '\n';
	std::cout << "GausPiK NDF: " << fGausPiK->GetNDF() << '\n';

	auto* fGausDecayProd{new TF1{"fGausDecayProd", "gausn", 0., 5.}};
	setFitStyle(fGausDecayProd);
	fGausDecayProd->SetParameter(0, 800.);
	fGausDecayProd->SetParameter(1, 0.9);
	fGausDecayProd->SetParameter(2, 0.05);
	hInvMassDecayProd->Fit(fGausDecayProd, "QN");
	for (int i{0}; i < 3; ++i)
	{
		std::cout << "GausDecayProd fit parameter " << i << ": " << fGausDecayProd->GetParameter(i) << " +/- "
				  << fGausDecayProd->GetParError(i) << '\n';
	}
	std::cout << "GausDecayProd chi2/NDF: " << fGausDecayProd->GetChisquare() / fGausDecayProd->GetNDF() << '\n';
	std::cout << "GausDecayProd chi2 prob: " << fGausDecayProd->GetProb() << '\n';
	std::cout << "GausDecayProd NDF: " << fGausDecayProd->GetNDF() << '\n';

	// Draw each histo in a canvas
	std::array<TCanvas*, 14> canvases;
	// Don't show canvases on screen
	gROOT->SetBatch(kTRUE);
	canvases[0] = new TCanvas{"cParticleTypes", "Particle types", 800, 600};
	hParticleTypes->Draw();
	canvases[1] = new TCanvas{"cPhi", "Phi", 800, 600};
	hPhi->Draw();
	canvases[2] = new TCanvas{"cTheta", "Theta", 800, 600};
	hTheta->Draw();
	canvases[3] = new TCanvas{"cImpulse", "Impulse", 800, 600};
	hImpulse->Draw();
	canvases[4] = new TCanvas{"cTransverseImpulse", "Transverse impulse", 800, 600};
	hTransverseImpulse->Draw();
	canvases[5] = new TCanvas{"cEnergy", "Energy", 800, 600};
	hEnergy->Draw();
	canvases[6] = new TCanvas{"cInvMass", "Invariant mass", 800, 600};
	hInvMass->Draw();
	canvases[7] = new TCanvas{"cInvMassSameSign", "Invariant mass same sign", 800, 600};
	hInvMassSameSign->Draw();
	canvases[8] = new TCanvas{"cInvMassDiscSign", "Invariant mass disc sign", 800, 600};
	hInvMassDiscSign->Draw();
	canvases[9] = new TCanvas{"cInvMassPiKSame", "Invariant mass pi K same", 800, 600};
	hInvMassPiKSame->Draw();
	canvases[10] = new TCanvas{"cInvMassPiKDisc", "Invariant mass pi K disc", 800, 600};
	hInvMassPiKDisc->Draw();
	canvases[11] = new TCanvas{"cInvMassDecayProd", "Invariant mass decay products", 800, 600};
	hInvMassDecayProd->Draw();
	canvases[12] = new TCanvas{"cInvMassSubAll", "Invariant mass sub all", 800, 600};
	hInvMassSubAll->Draw();
	canvases[13] = new TCanvas{"cInvMassSubPiK", "Invariant mass sub pi K", 800, 600};
	hInvMassSubPiK->Draw();

	// Save each canvas as pdf, C and root file
	system("mkdir -p build/pdf");
	system("mkdir -p build/C");
	system("mkdir -p build/root");
	for (auto* canvas : canvases)
	{
		canvas->Print((std::string{"build/pdf/"} + canvas->GetName() + ".pdf").c_str());
		canvas->Print((std::string{"build/C/"} + canvas->GetName() + ".C").c_str());
		canvas->Print((std::string{"build/root/"} + canvas->GetName() + ".root").c_str());
	}

	auto* particles{new TCanvas{"particles", "Particle parameters", 800, 600}};
	particles->Divide(2, 2);
	particles->cd(1);
	hParticleTypes->Draw();
	particles->cd(2);
	hImpulse->Draw();
	fExpImpulse->Draw("SAME");
	particles->cd(3);
	hTheta->GetYaxis()->SetTitleOffset(1.6);
	hTheta->Draw();
	fUnifTheta->Draw("SAME");
	particles->cd(4);
	hPhi->GetYaxis()->SetTitleOffset(1.6);
	hPhi->Draw();
	fUnifPhi->Draw("SAME");

	auto* invMass{new TCanvas{"invMass", "Invariant masses", 800, 600}};
	invMass->Divide(1, 3);
	invMass->cd(1);
	hInvMassDecayProd->Draw();
	fGausDecayProd->Draw("SAME");
	invMass->cd(2);
	hInvMassSubAll->Draw();
	fGausAll->Draw("SAME");
	invMass->cd(3);
	hInvMassSubPiK->Draw();
	fGausPiK->Draw("SAME");

	particles->Print("build/particles.pdf");
	invMass->Print("build/invMass.pdf");
}